version: '2'
services:
  server:
    restart: always 
    build: ./
    working_dir: /usr/app
    command: bash -c "npm install && nodemon start"
    ports: 
      - "3010:3000"
    env_file:
      - ./.env
    mem_limit: 300m
